### PR TITLE
Better API utils (wrapper around $.ajax)

### PR DESCRIPTION
**Pull request by yuchi**
The diff says it all. Example:

``` js
API.post('/users/'+username+'/documents', {
  token: true,
  client: true,
  data: {
    document: { /*...*/ } // NOTICE: no JSON.stringify here!
  },
  success: function () { /*...*/ },
  error: function () { /*...*/ }
});
```

### CODE REVIEW

**Comment by yuchi** [comment]
@michael, we haven't talked about this util, so I made a PR instead of pushing to master. Guys, tell me what you think.

**Comment by michael** [comment]
Looks good. Will have a look and merge. Is it supposed to break anything or should it be safe to merge it in?

**Comment by yuchi** [comment]
It doesn't break anything it's just a different way to call `$.ajax`. I switched to it a single call (POST /publications) just to see if everything worked correctly.

**Comment by michael** [comment]
Will take care of this soon. We're almost feature complete on the Composer/Replication side.

**Comment by michael** [comment]
No longer needed since this has been abstracted away by https://github.com/substance/client.

**Pull request closed without merging**
