### PR TITLE
Allow CORS for grabbing documents/user info #197

### PR DESCRIPTION
**Pull request by yocontra**
Also done from my phone - untested. #197

### CODE REVIEW

**Comment by yocontra** [comment]
ping (sorry if i'm bothering - wrote a blog engine based on this and i'm excited to release it)

**Comment by michael** [comment]
Merged and updated the site. Please check if everything works for you. Thanks for the patch and sorry for taking me so long to merge.

**Comment by yocontra** [comment]
Hmmm this doesn't seem to have done it - still getting 

```
XMLHttpRequest cannot load http://substance.io/documents/wearefractal. Origin http://contra.github.com is not allowed by Access-Control-Allow-Origin.
```

The routes I added CORS to should include http://substance.io/documents/wearefractal right?

**Comment by michael** [comment]
Does it work when you test it against your local Substance instance? I haven't implemented CORS on the serverside yet, is there anything else I need to setup?

`res.header('Access-Control-Allow-Origin', '*');` This should actually allow all origins right?

**Comment by michael** [comment]
Pls jump on the Substance channel on freenode #_substance, so we can discuss ad-hoc.

**Comment by yocontra** [comment]
Ah I thought when you said "Merged and updated the site" you meant you implemented this change. This should be it - when an OPTIONS is sent to a route that responds with allowCORS it should receive the go ahead. \* does allow all origins. Hopping on IRC now

**Pull request merged**
